#!/usr/bin/python2.6
# EASY-INSTALL-ENTRY-SCRIPT: 'WsgiDAV==0.5.1.dev-20140220','console_scripts','seafdav'
__requires__ = 'WsgiDAV==0.5.1.dev-20140220'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('WsgiDAV==0.5.1.dev-20140220', 'console_scripts', 'seafdav')()
    )
