#!/bin/bash
domain=$(sudo yunohost app setting seafile domain)

cd /var/www/seafile/seafile-server-*
sudo ./seafile.sh stop
sudo ./seahub.sh stop

sudo rm -rf /var/www/seafile
sudo rm -f /etc/nginx/conf.d/$domain.d/seafile.conf