#!/bin/bash
domain=$(sudo yunohost app setting seafile domain)

cd /var/www/seafile/seafile-server-*
sudo ./seafile.sh stop
sudo ./seahub.sh stop

sudo rm -rf /var/www/seafile
sudo rm -f /etc/nginx/conf.d/$domain.d/seafile.conf
sudo rm -f /etc/init.d/seafile-server
sudo rm -f /etc/init/seafile-server.conf

ccnet_port=$(sudo yunohost app setting seafile ccnet_port)
seafile_port=$(sudo yunohost app setting seafile seafile_port)
seahub_port=$(sudo yunohost app setting seafile seahub_port)

sudo yunohost firewall deny $ccnet_port
sudo yunohost firewall deny $seafile_port
sudo yunohost firewall deny $seahub_port
